#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Skip tests for now until test setup is complete
# Replace with the following when tests are implemented:
# pnpm exec nx affected --target=test --base=HEAD~1
